version: '3'
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - RAIN_PERCENTAGE_THRESHOLD
      - SLACK_WEBHOOK_URL
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
